databases:
  - name: dtxyz
    databaseName: dtxyz
    user: dtxyz

services:
  - type: web
    name: dtxyz
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dtxyz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false